import { Injectable } from '@nestjs/common';
import { Post } from '../interface/blog.interface';

@Injectable()
export class BlogRepository {
  private posts: Post[] = [
    {
      id: 1,
      title: 'Title Teste',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam augue ex, posuere sit amet tempus vel, dapibus id tortor. Curabitur tincidunt facilisis dapibus. Integer sit amet neque nibh. Nulla nec justo facilisis, bibendum lorem vitae, iaculis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris at vehicula justo. Aliquam erat volutpat. Proin placerat dolor iaculis sapien gravida, nec accumsan nisl consequat. Suspendisse arcu nulla, commodo a ornare a, condimentum ac nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce feugiat bibendum ante, nec vestibulum ipsum rutrum sed. Phasellus vulputate, magna in mollis blandit, quam mi maximus orci, nec porttitor elit lectus in velit. Donec iaculis nisl mi. <br /> <br /> <br />Curabitur eget varius orci. Etiam imperdiet et nisi eu tincidunt. Integer in tincidunt justo, ut dapibus augue. Praesent fermentum nulla lectus, eu lacinia nulla luctus ut. Nam ligula arcu, sagittis in orci a, tincidunt dapibus nunc. Integer quis ultricies risus. Suspendisse et magna tincidunt, gravida diam sit amet, iaculis orci. Cras aliquet finibus mauris. Nam volutpat mollis velit sit amet placerat. Vestibulum lobortis massa in libero elementum, nec maximus risus viverra. In id sapien odio. Duis eleifend libero ut nisi lacinia sollicitudin. Fusce nunc nisl, porttitor eget ex sed, malesuada luctus urna. Nulla elementum efficitur odio. In pretium massa eget porttitor aliquam. <br /> <br /> <br />Curabitur a ex ligula. Nulla in tincidunt urna, nec tincidunt ante. Nullam sodales odio sit amet justo blandit, ac fringilla neque vulputate. Aliquam ac nulla placerat, convallis arcu et, semper leo. Phasellus dictum ultricies orci, eget faucibus ligula ultrices non. Nullam in erat posuere, lacinia turpis nec, volutpat sapien. Aliquam ut arcu eget magna consequat pretium. Nunc at efficitur tellus, vitae pulvinar quam. Nunc dignissim urna quis odio dignissim, eu efficitur leo ultrices. Mauris id lorem non eros ultrices dignissim fringilla vitae velit. Praesent sit amet metus augue. Phasellus pharetra lectus eget ligula sagittis pellentesque. Integer turpis mi, dictum convallis malesuada ut, feugiat sit amet quam. Quisque tempus lacus nibh, quis gravida tellus lacinia in. Phasellus at nisi pharetra, congue nisl ac, rhoncus mi. Praesent vitae aliquet nunc. Integer et lorem porta, gravida ipsum id, lobortis felis. Vestibulum rutrum molestie velit, quis fermentum neque accumsan ac.',
      applicant: 'Test User',
      bloodType: 'O+',
      image:
        'https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZG9jdG9yfGVufDB8fDB8fHww',
    },
    {
      id: 2,
      title: 'Title Teste',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam augue ex, posuere sit amet tempus vel, dapibus id tortor. Curabitur tincidunt facilisis dapibus. Integer sit amet neque nibh. Nulla nec justo facilisis, bibendum lorem vitae, iaculis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris at vehicula justo. Aliquam erat volutpat. Proin placerat dolor iaculis sapien gravida, nec accumsan nisl consequat. Suspendisse arcu nulla, commodo a ornare a, condimentum ac nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce feugiat bibendum ante, nec vestibulum ipsum rutrum sed. Phasellus vulputate, magna in mollis blandit, quam mi maximus orci, nec porttitor elit lectus in velit. Donec iaculis nisl mi. <br /> <br /> <br />Curabitur eget varius orci. Etiam imperdiet et nisi eu tincidunt. Integer in tincidunt justo, ut dapibus augue. Praesent fermentum nulla lectus, eu lacinia nulla luctus ut. Nam ligula arcu, sagittis in orci a, tincidunt dapibus nunc. Integer quis ultricies risus. Suspendisse et magna tincidunt, gravida diam sit amet, iaculis orci. Cras aliquet finibus mauris. Nam volutpat mollis velit sit amet placerat. Vestibulum lobortis massa in libero elementum, nec maximus risus viverra. In id sapien odio. Duis eleifend libero ut nisi lacinia sollicitudin. Fusce nunc nisl, porttitor eget ex sed, malesuada luctus urna. Nulla elementum efficitur odio. In pretium massa eget porttitor aliquam. <br /> <br /> <br />Curabitur a ex ligula. Nulla in tincidunt urna, nec tincidunt ante. Nullam sodales odio sit amet justo blandit, ac fringilla neque vulputate. Aliquam ac nulla placerat, convallis arcu et, semper leo. Phasellus dictum ultricies orci, eget faucibus ligula ultrices non. Nullam in erat posuere, lacinia turpis nec, volutpat sapien. Aliquam ut arcu eget magna consequat pretium. Nunc at efficitur tellus, vitae pulvinar quam. Nunc dignissim urna quis odio dignissim, eu efficitur leo ultrices. Mauris id lorem non eros ultrices dignissim fringilla vitae velit. Praesent sit amet metus augue. Phasellus pharetra lectus eget ligula sagittis pellentesque. Integer turpis mi, dictum convallis malesuada ut, feugiat sit amet quam. Quisque tempus lacus nibh, quis gravida tellus lacinia in. Phasellus at nisi pharetra, congue nisl ac, rhoncus mi. Praesent vitae aliquet nunc. Integer et lorem porta, gravida ipsum id, lobortis felis. Vestibulum rutrum molestie velit, quis fermentum neque accumsan ac.',
      applicant: 'Test User',
      bloodType: 'O+',
      image:
        'https://images.unsplash.com/photo-1504813184591-01572f98c85f?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGRvY3RvcnxlbnwwfHwwfHx8MA%3D%3D',
    },
    {
      id: 3,
      title: 'Title Teste',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam augue ex, posuere sit amet tempus vel, dapibus id tortor. Curabitur tincidunt facilisis dapibus. Integer sit amet neque nibh. Nulla nec justo facilisis, bibendum lorem vitae, iaculis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris at vehicula justo. Aliquam erat volutpat. Proin placerat dolor iaculis sapien gravida, nec accumsan nisl consequat. Suspendisse arcu nulla, commodo a ornare a, condimentum ac nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce feugiat bibendum ante, nec vestibulum ipsum rutrum sed. Phasellus vulputate, magna in mollis blandit, quam mi maximus orci, nec porttitor elit lectus in velit. Donec iaculis nisl mi. <br /> <br /> <br />Curabitur eget varius orci. Etiam imperdiet et nisi eu tincidunt. Integer in tincidunt justo, ut dapibus augue. Praesent fermentum nulla lectus, eu lacinia nulla luctus ut. Nam ligula arcu, sagittis in orci a, tincidunt dapibus nunc. Integer quis ultricies risus. Suspendisse et magna tincidunt, gravida diam sit amet, iaculis orci. Cras aliquet finibus mauris. Nam volutpat mollis velit sit amet placerat. Vestibulum lobortis massa in libero elementum, nec maximus risus viverra. In id sapien odio. Duis eleifend libero ut nisi lacinia sollicitudin. Fusce nunc nisl, porttitor eget ex sed, malesuada luctus urna. Nulla elementum efficitur odio. In pretium massa eget porttitor aliquam. <br /> <br /> <br />Curabitur a ex ligula. Nulla in tincidunt urna, nec tincidunt ante. Nullam sodales odio sit amet justo blandit, ac fringilla neque vulputate. Aliquam ac nulla placerat, convallis arcu et, semper leo. Phasellus dictum ultricies orci, eget faucibus ligula ultrices non. Nullam in erat posuere, lacinia turpis nec, volutpat sapien. Aliquam ut arcu eget magna consequat pretium. Nunc at efficitur tellus, vitae pulvinar quam. Nunc dignissim urna quis odio dignissim, eu efficitur leo ultrices. Mauris id lorem non eros ultrices dignissim fringilla vitae velit. Praesent sit amet metus augue. Phasellus pharetra lectus eget ligula sagittis pellentesque. Integer turpis mi, dictum convallis malesuada ut, feugiat sit amet quam. Quisque tempus lacus nibh, quis gravida tellus lacinia in. Phasellus at nisi pharetra, congue nisl ac, rhoncus mi. Praesent vitae aliquet nunc. Integer et lorem porta, gravida ipsum id, lobortis felis. Vestibulum rutrum molestie velit, quis fermentum neque accumsan ac.',
      applicant: 'Test User',
      bloodType: 'O+',
      image:
        'https://images.unsplash.com/photo-1609188076864-c35269136b09?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzN8fGRvY3RvcnxlbnwwfHwwfHx8MA%3D%3D',
    },
    {
      id: 4,
      title: 'Title Teste',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam augue ex, posuere sit amet tempus vel, dapibus id tortor. Curabitur tincidunt facilisis dapibus. Integer sit amet neque nibh. Nulla nec justo facilisis, bibendum lorem vitae, iaculis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris at vehicula justo. Aliquam erat volutpat. Proin placerat dolor iaculis sapien gravida, nec accumsan nisl consequat. Suspendisse arcu nulla, commodo a ornare a, condimentum ac nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce feugiat bibendum ante, nec vestibulum ipsum rutrum sed. Phasellus vulputate, magna in mollis blandit, quam mi maximus orci, nec porttitor elit lectus in velit. Donec iaculis nisl mi. <br /> <br /> <br />Curabitur eget varius orci. Etiam imperdiet et nisi eu tincidunt. Integer in tincidunt justo, ut dapibus augue. Praesent fermentum nulla lectus, eu lacinia nulla luctus ut. Nam ligula arcu, sagittis in orci a, tincidunt dapibus nunc. Integer quis ultricies risus. Suspendisse et magna tincidunt, gravida diam sit amet, iaculis orci. Cras aliquet finibus mauris. Nam volutpat mollis velit sit amet placerat. Vestibulum lobortis massa in libero elementum, nec maximus risus viverra. In id sapien odio. Duis eleifend libero ut nisi lacinia sollicitudin. Fusce nunc nisl, porttitor eget ex sed, malesuada luctus urna. Nulla elementum efficitur odio. In pretium massa eget porttitor aliquam. <br /> <br /> <br />Curabitur a ex ligula. Nulla in tincidunt urna, nec tincidunt ante. Nullam sodales odio sit amet justo blandit, ac fringilla neque vulputate. Aliquam ac nulla placerat, convallis arcu et, semper leo. Phasellus dictum ultricies orci, eget faucibus ligula ultrices non. Nullam in erat posuere, lacinia turpis nec, volutpat sapien. Aliquam ut arcu eget magna consequat pretium. Nunc at efficitur tellus, vitae pulvinar quam. Nunc dignissim urna quis odio dignissim, eu efficitur leo ultrices. Mauris id lorem non eros ultrices dignissim fringilla vitae velit. Praesent sit amet metus augue. Phasellus pharetra lectus eget ligula sagittis pellentesque. Integer turpis mi, dictum convallis malesuada ut, feugiat sit amet quam. Quisque tempus lacus nibh, quis gravida tellus lacinia in. Phasellus at nisi pharetra, congue nisl ac, rhoncus mi. Praesent vitae aliquet nunc. Integer et lorem porta, gravida ipsum id, lobortis felis. Vestibulum rutrum molestie velit, quis fermentum neque accumsan ac.',
      applicant: 'Test User',
      bloodType: 'O+',
      image:
        'https://images.unsplash.com/photo-1590611936760-eeb9bc598548?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDh8fGRvY3RvcnxlbnwwfHwwfHx8MA%3D%3D',
    },
  ];

  getPostList() {
    return this.posts;
  }

  getPost(id: number) {
    return this.posts.find((post) => post.id === id);
  }
}
